spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/exp
    username: yeachan
    password: tlsdPcks05
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
