spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/exp
    username: yeachan
    password: tlsdPcks05

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always

jwt:
  header: Authorization
  secret: ZXhwLXNwcmluZ2Jvb3Qtand0LXNlY3JldC1rZXktZm9yLXNpZ2luLWtleS0yMDIzLTA4LTI0LTIxLTQ1LWtpdAo=
  token-validity-in-second: 86400

logging:
  level:
    root: info